plugins {
    id 'com.android.application'
}

android {
    namespace 'ca.dnamobile.droidbridgelauncher'
    compileSdk 35

    defaultConfig {
        applicationId 'ca.dnamobile.droidbridgelauncher'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {}
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':methods_injector_agent')
    implementation project(':nativeglfw')
}
