plugins {
    id 'com.android.library'
}

android {
    namespace 'ca.dnamobile.methodsinjectoragent'
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
